### ISSUE TITLE
Titles sources are not translated

### ISSUE THREAD

**Issue by pyrog** [taginfo/taginfo#103]
See http://taginfo.openstreetmap.org/sources

Keys exist in .yml files:

```
sources:
    master:
        name: Maître
    db:
        name: Base de données
     wiki:
        name: Wiki
    josm:
        name: JOSM
    languages:
        name: Langues
    projects:
        name: Projets
```
