### ISSUE TITLE
Use Wikibase data instead of parsing wiki text

### ISSUE THREAD

**Issue by nyurik** [taginfo/taginfo#248]
Now that most of the `{{KeyDescription}}` and `{{ValueDescription}}` data has been copied from the wiki into to the new structured `Item` pages, TagInfo can quickly get that data without the error prone wikimarkup parsing, in all available languages.

See [documentation](https://wiki.openstreetmap.org/wiki/OpenStreetMap:Wikibase)

The simplest way to minimize code changes might be to use a simple Python script (I can write that) to download all available data and store it as a JSON file.  The download from MediaWiki API would take about 5-15 seconds, so it can be done regularly.  As more interesting information becomes available, it would be very easy to adjust the script to get additional fields.

I could write such a script if someone would describe exactly which fields are needed by TagInfo, and in what structure. Here's one example - dictionary of keys, and for known tags, includes key values.  Each key and value may contain labels, descriptions, links to the wiki pages.

```yaml
{
  "keys": {
    "name:en": {
      "labels": { "en": "Name in English", "ru": "...", ...},
      "descriptions": { "en": "This key contains names in English", "fr": "...", ...},
      "wikipages": {"en": "https://wiki.osm.org/wiki/Key:name:en", ...},
      "use-on": ["node", "way", "area", "relation"],
      "image": "https://...",
    },
    "bridge:movable": {
      "labels": {...}, "descriptions": {...}, ...
      "values": {
        "submersible": {
          "labels": {...}, "descriptions": {...}, ...
        },
        # ... other values for the key "bridge:movable"
      }
    },
    # ... other keys
  },
  # ... other data may go here, e.g. relations info once it is parsed
}
```
